#config_version=5 

mode:
  start_events: ball_starting
  #stop_events: mode_franklin_hurry_up_started mode_franklin_frenzy_started
  priority: 500

event_player:
  top_turbo_bumper_hit:
    - cmd_show_pop_bumper_slide
    - cmd_show_old_man
  left_turbo_bumper_hit:
    - cmd_show_pop_bumper_slide
    - cmd_show_hitchhiker
  right_turbo_bumper_hit:
    - cmd_show_pop_bumper_slide
    - cmd_show_leatherface
  cmd_show_pop_bumper_slide:
    - cmd_increase_mystery_meater_count
    - cmd_animate_progress_bar
  player_v_mystery_meater_count:
    cmd_update_progress_bar_width:
      new_width:
        value: 57.0 * current_player.v_mystery_meater_count / 50.0
        type: float

counters:
  mystery_meater_progress_counter:
    count_events: cmd_increase_mystery_meater_count
    count_complete_value: 50
    disable_on_complete: True
    enable_events: mode_pop_bumpers_started


variable_player:
  logicblock_mystery_meater_progress_counter_hit:
    v_mystery_meater_count: 1

animations:
  character_hit:
    - property: opacity
      value: 1
      duration: 0
    - property: opacity
      value: 1
      duration: 0.30
    - property: opacity
      duration: 0
      value: 0

widgets:

widget_player:
  pop_bumpers_mode_started:
    progress_bar_widget:
      slide: pop_bumper_slide

      #  cmd_update_progress_bar_width:
      #    progress_bar_widget:
      #      widget_settings:
      #        width: (new_width)

show_player:
  cmd_update_progress_bar_width:
    family_bumper_show:
      action: play
      events_when_completed: cmd_hide_family_bumpers
      loops: 0
      show_tokens:
        new_width: (current_player.v_mystery_meater_count)
  cmd_hide_family_bumpers:
    family_bumper_show:
      action: stop


  

      #slide_player:
      #  cmd_show_pop_bumper_slide:
      #    pop_bumper_slide:
      #      priority: 300
      #      expire: 2s
