#config_version=5 

mode:
  start_events: ball_starting
  #stop_events: mode_franklin_hurry_up_started mode_franklin_frenzy_started
  priority: 500

event_player:
  top_turbo_bumper_hit:
    - cmd_show_pop_bumper_slide
    - cmd_show_old_man
  left_turbo_bumper_hit:
    - cmd_show_pop_bumper_slide
    - cmd_show_hitchhiker
  right_turbo_bumper_hit:
    - cmd_show_pop_bumper_slide
    - cmd_show_leatherface
  cmd_show_pop_bumper_slide:
    - cmd_increase_mystery_meater_count
    - cmd_animate_progress_bar

counters:
  mystery_meater_progress_counter:
    count_events: cmd_increase_mystery_meater_count
    count_complete_value: 50
    disable_on_complete: True
    enable_events: mode_pop_bumpers_started


variable_player:
  logicblock_mystery_meater_progress_counter_hit:
    v_mystery_meater_count:
      action: set
      float: 57.0 * (current_player.v_mystery_meater_count + 1) / 50.0

animations:
  character_hit:
    - property: opacity
      value: 1
      duration: 0
    - property: opacity
      value: 1
      duration: 0.30
    - property: opacity
      duration: 0
      value: 0

slides:
  pop_bumper_slide:
    widgets:
    - type: text
      text: MYSTERY MEATER
      style: dmd_small
      anchor_x: 0
      anchor_y: 0
      x: 1
      y: 0
    - type: image
      image: pops_hitchhiker_up_v2
      anchor_x: 0
      anchor_y: 0
      x: 0
      y: 6
      opacity: 0
      animations:
        cmd_show_hitchhiker: character_hit
    - type: image
      image: pops_leatherface_up_v2
      opacity: 0
      anchor_x: 0
      anchor_y: 0
      x: 0
      y: 6
      animations:
        cmd_show_leatherface: character_hit
    - type: image
      image: pops_oldman_up_v2
      anchor_x: 0
      anchor_y: 0
      x: 0
      y: 6
      opacity: 0
      animations:
        cmd_show_old_man: character_hit
    - type: image
      image: pops_base_v3
      anchor_x: 0
      anchor_y: 0
      x: 0
      y: 6
    - type: rectangle
      color: white
      anchor_x: 0
      anchor_y: 0
      x: 71
      y: 0
      width: 0
      height: 5
      animations:
        cmd_animate_progress_bar:
        - property: width
          value: current_player.v_mystery_meater_count
    - type: rectangle
      color: black
      anchor_x: 0
      anchor_y: 0
      x: 72
      y: 1
      width: 55
      height: 3
    - type: rectangle
      color: white
      anchor_x: 0
      anchor_y: 0
      x: 71
      y: 0
      width: 57
      height: 5

slide_player:
  cmd_show_pop_bumper_slide:
    pop_bumper_slide:
      priority: 300
      expire: 2s
