#config_version=5 

mode:
  start_events: ball_starting
  #stop_events: mode_franklin_hurry_up_started mode_franklin_frenzy_started
  priority: 500

event_player:
  top_turbo_bumper_hit{current_player.v_mystery_meater_complete==0}:
    - cmd_show_pop_bumper_slide
    - cmd_show_old_man
  left_turbo_bumper_hit{current_player.v_mystery_meater_complete==0}:
    - cmd_show_pop_bumper_slide
    - cmd_show_hitchhiker
  right_turbo_bumper_hit{current_player.v_mystery_meater_complete==0}:
    - cmd_show_pop_bumper_slide
    - cmd_show_leatherface
  cmd_show_pop_bumper_slide{current_player.v_mystery_meater_complete==0}:
    - cmd_make_family_slide_visible
    - cmd_increase_mystery_meater_count
  player_v_mystery_meater_count{value==50}:
    - cmd_mystery_meater_completed
  #cmd_mystery_meater_completed:
  timer_my_test_timer_complete:
    cmd_custom_magna_vuk_handler:
      switch_hit_evnt: cmd_play_mystery_animation
      fire_vuk_evnt: cmd_mystery_animation_complete
      coil_direction: left

variable_player:
  cmd_increase_mystery_meater_count:
    v_mystery_meater_count: 1
  player_v_mystery_meater_count{value<50}:
    v_mystery_meater_width:
      float: 57.0 * current_player.v_mystery_meater_count / 50.0
      action: set
  cmd_mystery_meater_completed:
    v_mystery_meater_complete: 1
  cmd_reset_mystery_meater:
    v_mystery_meater_complete: 0

animations:
  character_hit:
    - property: opacity
      value: 1
      duration: 0
    - property: opacity
      value: 1
      duration: 0.30
    - property: opacity
      duration: 0
      value: 0

slides:
  pop_bumper_slide:
    widgets:
    - type: text
      text: MYSTERY MEATER
      style: dmd_small
      anchor_x: 0
      anchor_y: 0
      x: 1
      y: 0
    - type: image
      image: pops_hitchhiker_up_v2
      anchor_x: 0
      anchor_y: 0
      x: 0
      y: 6
      opacity: 0
      animations:
        cmd_show_hitchhiker: character_hit
    - type: image
      image: pops_leatherface_up_v2
      opacity: 0
      anchor_x: 0
      anchor_y: 0
      x: 0
      y: 6
      animations:
        cmd_show_leatherface: character_hit
    - type: image
      image: pops_oldman_up_v2
      anchor_x: 0
      anchor_y: 0
      x: 0
      y: 6
      opacity: 0
      animations:
        cmd_show_old_man: character_hit
    - type: rectangle
      color: white
      anchor_x: 0
      anchor_y: 0
      x: 71
      y: 0
      z: 500
      width: 1
      height: 5
      animations:
        player_v_mystery_meater_width:
          - property: width
            value: (value)
            duration: 0
    - type: image
      image: pops_base_v3
      anchor_x: 0
      anchor_y: 0
      x: 0
      y: 6
    - type: rectangle
      color: black
      anchor_x: 0
      anchor_y: 0
      x: 72
      y: 1
      width: 55
      height: 3
    - type: rectangle
      color: white
      anchor_x: 0
      anchor_y: 0
      x: 71
      y: 0
      width: 57
      height: 5
  shoot_the_slaughter_house_for_mystery_slide:
    widgets:
    - type: text
      text: SHOOT THE SLAUGHTER HOUSE
      style: dmd_big
      anchor_x: 0
      anchor_y: 0
      x: 1
      y: 0

slide_player:
  cmd_make_family_slide_visible:
    pop_bumper_slide:
      priority: 300
      expire: 2s
  cmd_mystery_meater_completed:
    shoot_the_slaughter_house_for_mystery_slide:
      priority: 400
      expire: 2s

show_player:
  cmd_mystery_meater_completed:
    fast_flash:
      action: play
      show_tokens:
        lights:
          slaughter_house
