#config_version=5 

mode:
  start_events: ball_starting
  #stop_events: mode_franklin_hurry_up_started mode_franklin_frenzy_started
  priority: 500

event_player:
  top_turbo_bumper_hit{current_player.v_mystery_meater_complete==0}:
    - cmd_show_pop_bumper_slide
    - cmd_show_old_man
  left_turbo_bumper_hit{current_player.v_mystery_meater_complete==0}:
    - cmd_show_pop_bumper_slide
    - cmd_show_hitchhiker
  right_turbo_bumper_hit{current_player.v_mystery_meater_complete==0}:
    - cmd_show_pop_bumper_slide
    - cmd_show_leatherface
  cmd_show_pop_bumper_slide{current_player.v_mystery_meater_complete==0}:
    - cmd_increase_mystery_meater_count
    - cmd_make_family_slide_visible
  player_v_mystery_meater_count{value==machine.pop_bumper_mystery_complete_count}:
    - cmd_mystery_meater_completed
  cmd_mystery_meater_completed:
    cmd_custom_magna_vuk_handler:
      switch_hit_evnt: cmd_play_mystery_show
      fire_vuk_evnt: cmd_mystery_show_complete
      coil_direction: left
  cmd_play_mystery_show:
    - cmd_main_music_volume_down
  cmd_mystery_show_complete:
    - cmd_main_music_volume_up
variable_player:
  cmd_increase_mystery_meater_count:
    v_mystery_meater_count: 1
  player_v_mystery_meater_count{value<machine.pop_bumper_mystery_complete_count}:
    v_mystery_meater_width:
      float: 57.0 * current_player.v_mystery_meater_count / machine.pop_bumper_mystery_complete_count
      action: set
  cmd_mystery_meater_completed:
    v_mystery_meater_complete: 1
  cmd_reset_mystery_meater:
    v_mystery_meater_complete: 0

animations:
  character_hit:
    - property: opacity
      value: 1
      duration: 0
    - property: opacity
      value: 1
      duration: 0.30
    - property: opacity
      duration: 0
      value: 0

slides:
  shoot_the_slaughter_house_for_mystery_slide:
    widgets:
    - type: text
      text: SHOOT THE
      style: dmd_big
      anchor_x: 0
      anchor_y: 0
      x: 57
      y: 16
      animations:
        show_slide: sawyer_flash
    - type: text
      text: SLAUGHTERHOUSE
      style: dmd_small
      anchor_x: 0
      anchor_y: 0
      x: 53
      y: 8
      animations:
        show_slide: sawyer_flash
    - type: image
      image: shoot_the_slaughterhouse_v1
      anchor_x: left
      anchor_y: bottom
      x: 0
      y: 0

slide_player:
  cmd_mystery_meater_completed:
    shoot_the_slaughter_house_for_mystery_slide:
      priority: 400
      expire: 2s

show_player:
  cmd_mystery_meater_completed:
    fast_flash:
      action: play
      show_tokens:
        lights:
          slaughter_house
  cmd_mystery_show_complete:
    fast_flash:
      action: stop
  cmd_make_family_slide_visible:
    family_bumper_show:
      action: play
      events_when_completed: cmd_hide_family_bumpers
      loops: 0
      show_tokens:
        new_width: (current_player.v_mystery_meater_width)
  cmd_hide_family_bumpers:
    family_bumper_show:
      action: stop
  cmd_play_mystery_show:
    mystery_show:
      action: play
      events_when_completed: cmd_mystery_show_complete
      loops: 0

sound_player:
  cmd_play_mystery_show:
    mystery_sound:
      action: play
      loops: 0
  top_turbo_bumper_hit: ding_2
  left_turbo_bumper_hit: ding_2
  right_turbo_bumper_hit: ding_2
