#config_version=5

mode:
  start_events: logicblock_mask_total_counter_complete
  stop_events: timer_mask_making_countdown_complete
  priority: 250

timers:
  mask_making_countdown:
    debug: true
    start_value: settings.mask_making_timer_total
    end_value: 0
    direction: down
    start_running: True

variable_player:
  mode_mask_making_started:
    mask_making_countdown_value:
      int: settings.mask_making_timer_total
      action: set
  timer_mask_making_countdown_tick:
    mask_making_countdown_value:
      int: device.timers.mask_making_countdown.ticks
      action: set

show_player:
  mode_mask_making_started: mask_making
  timer_mask_making_countdown_tick: mask_making
