#config_version=5 

mode:
  start_events: ball_starting
  priority: 500

event_player:
  s_captive_ball_target_active:
    - cmd_count_sftg
  logicblock_grave_save_counter_complete:
    - cmd_sftg_enabled
  s_left_outlane_active{current_player.v_sftg_enabled==1}:
    - cmd_sftg_start_ball_save
  logicblock_grave_save_counter_hit:
    - cmd_play_bump_show
    - cmd_play_bump_audio
  ball_save_sftg_ball_save_saving_ball:
    - cmd_play_save_show
    - cmd_play_save_audio

sound_player:
  cmd_play_bump_audio: sftg_bump
  cmd_play_save_audio: sftg_save

show_player:
  cmd_play_bump_show:
    grave_bump_show:
      action: play
      loops: 0
  logicblock_grave_save_counter_hit{count==1}:
    on:
      show_tokens:
        lights: sftg_save
  logicblock_grave_save_counter_hit{count==2}:
    on:
      show_tokens:
        lights: sftg_save, sftg_for_the
  logicblock_grave_save_counter_complete:
    on:
      show_tokens:
        lights: sftg_save, sftg_for_the, sftg_grave, l_sftg_enabled
  cmd_play_save_show:
    sftg_show:
      action: play
      loops: 0
      events_when_completed:
        - cmd_sftg_clear_the_lights
        - cmd_sftg_restart_counter
  cmd_sftg_clear_the_lights:
    off:
      show_tokens:
        lights: sftg_save, sftg_for_the, sftg_grave, l_sftg_enabled

variable_player:
  cmd_sftg_enabled:
    v_sftg_enabled:
      int: 1
      action: set

counters:
  grave_save_counter:
    count_events: cmd_count_sftg
    disable_on_complete: True
    count_complete_value: 3
    restart_events: cmd_sftg_restart_counter

ball_saves:
  sftg_ball_save:
    active_time: 3s
    enable_events: cmd_sftg_start_ball_save
    auto_launch: yes
    balls_to_save: 1
    eject_delay: 4.2s
