#config_version=5

drop_targets:
  top:
    switch: s_3_bank_drop_top
    reset_coil: c_3_bank_drop_target_reset
  mid:
    switch: s_3_bank_drop_mid
    reset_coil: c_3_bank_drop_target_reset
  bottom:
    switch: s_3_bank_drop_mid
    reset_coil: c_3_bank_drop_target_reset

drop_target_banks:
  drop: #TODO: needs a rename
    drop_targets: top, mid, bottom
    reset_coils: c_3_bank_drop_target_reset
    reset_on_complete: 0.5s
