#config_version=5

flippers:
  left_flipper:
    main_coil: c_flipper_left
    activation_switch: s_left_flipper
    #enable_events: machine_reset_phase_3 # enable to turn on automatically
  right_flipper:
    main_coil: c_flipper_right
    activation_switch: s_right_flipper
    #enable_events: machine_reset_phase_3 # enable to turn on automatically
