#config_version=5

modes:
  - base
  - bonus
  - chainsaw
  - franklin
  - franklin_frenzy
  - franklin_hurry_up
  - help
  - mask
  - meathook
  - pop_bumpers
  - save_from_the_grave
  - standard_extra_ball
