#config_version=5

sounds:
  organ:
    file: organ.wav
  intro_jazz:
    file: ffab_loop.wav
    mode_end_action: stop
  attract_dark:
    file: dark_open.wav
  open_speech:
    file: open_speech.wav
  franklin_whip_cmon:
    file: franklin_whip_cmon.wav
    volume: 1.0
  mask_slice:
    file: mask_slice.wav
    volume: 1.0
  franklin_hurry_up:
    file: franklin_in_trouble_v1.wav
    mode_end_action: stop
    volume: 1.0
  franklin_fun:
    file: franklin_fun.wav
    mode_end_action: stop
    volume: 1.0
