#config_version=5

machine_vars:
  magnavuk_auto_fire:
    initial_value: 1
  mask_completion_count_for_mask_making:
    initial_value: 3

player_vars:
  mask_completion_total:
    initial_value: 0
  mask_making_countdown_value:
    initial_value: 10
  franklin_f_start_opacity:
    initial_value: 0
  franklin_f_end_opacity:
    initial_value: 0
  franklin_r_start_opacity:
    initial_value: 0
  franklin_r_end_opacity:
    initial_value: 0
  franklin_a_start_opacity:
    initial_value: 0
  franklin_a_end_opacity:
    initial_value: 0
  franklin_n_start_opacity:
    initial_value: 0
  franklin_n_end_opacity:
    initial_value: 0
  franklin_k_start_opacity:
    initial_value: 0
  franklin_k_end_opacity:
    initial_value: 0
  franklin_l_start_opacity:
    initial_value: 0
  franklin_l_end_opacity:
    initial_value: 0
  franklin_i_start_opacity:
    initial_value: 0
  franklin_i_end_opacity:
    initial_value: 0
  franklin_n2_start_opacity:
    initial_value: 0
  franklin_n2_end_opacity:
    initial_value: 0
