#config_version=5

mode:
  start_events: ball_starting, mode_mask_making_stopped
  stop_events: logicblock_mask_total_counter_complete
  priority: 200

counters:
  mask_counter:
    count_events: right_ramp_hit
    disable_on_complete: False
    reset_on_complete: True
    count_complete_value: 4
  mask_total_counter:
    disable_on_complete: False
    reset_on_complete: True
    count_events: logicblock_mask_counter_complete
    count_complete_value: (machine.mask_completion_count_for_mask_making)
    persist_state: true

show_player:
  logicblock_mask_counter_hit{count==1}:
    on:
      show_tokens:
        lights: fire_f
    mask1:
      loops: 0
      show_tokens:
        mask_image: mask_m_v1
  logicblock_mask_counter_hit{count==2}:
    on:
      show_tokens:
        lights: fire_f, fire_i
    mask1:
      loops: 0
      show_tokens:
        mask_image: mask_a_v1
  logicblock_mask_counter_hit{count==3}:
    on:
      show_tokens:
        lights: fire_f, fire_i, fire_r
    mask1:
      loops: 0
      show_tokens:
        mask_image: mask_s_v1
  logicblock_mask_total_counter_hit:
    off:
      show_tokens:
        lights: fire_f, fire_i, fire_r, fire_e
    flash:
      loops: 1
      speed: 4
      show_tokens:
        lights: fire_f, fire_i, fire_r, fire_e
  logicblock_mask_total_counter_hit{count<(machine.mask_completion_count_for_mask_making)}:
    mask1:
      loops: 0
      show_tokens:
        mask_image: mask_k_v1

sound_player:
  logicblock_mask_counter_hit:
    mask_slice:
      action: play
      loops: 0

variable_player:
  logicblock_mask_counter_hit{count==1}:
    score: 25000
  logicblock_mask_counter_hit{count==2}:
    score: 35000
  logicblock_mask_counter_hit{count==3}:
    score: 50000
  logicblock_mask_total_counter_hit:
    score: 100000
    mask_completion_total: 1
