#config_version=5

# the chainsaw targets rev full when in multiball

mode:
  start_events: ball_starting
  #stop_events: mode_franklin_hurry_up_started mode_franklin_frenzy_started
  priority: 500

shots:
  # target shots
  chain_c_shot:
    switch: s_chain_target_c
    show_tokens:
      light: chain_target_c
  chain_h_shot:
    switch: s_chain_target_h
    show_tokens:
      light: chain_target_h
  chain_a_shot:
    switch: s_chain_target_a
    show_tokens:
      light: chain_target_a
  chain_i_shot:
    switch: s_chain_target_i
    show_tokens:
      light: chain_target_i
  chain_n_shot:
    switch: s_chain_target_n
    show_tokens:
      light: chain_target_n
  saw_s_shot:
    switch: s_saw_target_s
    show_tokens:
      light: saw_target_s
  saw_a_shot:
    switch: s_saw_target_a
    show_tokens:
      light: saw_target_a
  saw_w_shot:
    switch: s_saw_target_w
    show_tokens:
      light: saw_target_w

  # multiball shots
  gas_station_shot:
    switch: s_jump_ball_vuk

multiballs:
  mb_chainsaw_multiball:
    ball_count: 2
    ball_count_type: add
    shoot_again: 10s
    start_events: cmd_start_chainsaw_multiball

light_player:
  cmd_start_chainsaw_multiball:
    left_orbit_arrow: ff
    captive_ball_arrow: ff
    basket_ramp_arrow: ff
    gas_station_arrow: ff
    right_ramp_arrow: ff
    right_orbit_arrow: ff
  cmd_turn_off_light_left_orbit:
    left_orbit_arrow: 0
  cmd_turn_off_light_left_ramp:
    basket_ramp_arrow: 0
  cmd_turn_off_light_right_ramp:
    right_ramp_arrow: 0
  cmd_turn_off_light_right_orbit:
    right_orbit_arrow: 0

shot_groups:
  chainsaw_shot_group:
    shots:
      chain_c_shot,
      chain_h_shot,
      chain_a_shot,
      chain_i_shot,
      chain_n_shot,
      saw_s_shot,
      saw_a_shot,
      saw_w_shot
    reset_events:
      cmd_reset_chainsaw_shot_group

event_player:
  mode_chainsaw_started:
    - cmd_reset_chainsaw_progression_slide
  chainsaw_shot_group_complete:
    - cmd_light_multiball
  ball_hold_bh_sawyer_house_full:
    - cmd_start_chainsaw_multiball_intro
    - cmd_start_chainsaw_multiball_start_timer
    - cmd_stop_music
  timer_chainsaw_multiball_start_timer_complete:
    - cmd_start_chainsaw_multiball
  cmd_start_chainsaw_multiball:
    - cmd_disable_sawyer_ball_hold
    - cmd_release_sawyer_ball
    - cmd_stop_sawyer_light_flashing
    - cmd_start_shoot_again_flash
    - cmd_start_chainsaw_multiball_music
    - cmd_set_chainsaw_variable_on
  multiball_mb_chainsaw_multiball_ended:
    - cmd_chainsaw_multiball_ended
    - cmd_start_base_music
    - cmd_stop_chainsaw_multiball_music
    - cmd_set_chainsaw_variable_off
  cmd_chainsaw_multiball_ended:
    - cmd_reset_chainsaw_shot_group
  multiball_mb_chainsaw_multiball_shoot_again_ended:
    - cmd_stop_shoot_again_flash
  timer_shoot_the_house_timer_complete:
    - cmd_start_shoot_the_house
  left_orbit_hit{current_player.v_chainsaw_multiball_active==1}:
    - cmd_start_jackpot_slide
    - cmd_turn_off_light_left_orbit
  left_ramp_hit{current_player.v_chainsaw_multiball_active==1}:
    - cmd_start_jackpot_slide
    - cmd_turn_off_light_left_ramp
  right_ramp_hit{current_player.v_chainsaw_multiball_active==1}:
    - cmd_start_jackpot_slide
    - cmd_turn_off_light_right_ramp
  right_orbit_hit{current_player.v_chainsaw_multiball_active==1}:
    - cmd_start_jackpot_slide
    - cmd_turn_off_light_right_orbit

  # animation shots
  chain_c_shot_hit{advancing==True}:
    - cmd_play_rumble_sound
    - cmd_display_chainsaw_progression
    - cmd_play_chain_c_activated
  chain_h_shot_hit{advancing==True}:
    - cmd_play_rumble_sound
    - cmd_display_chainsaw_progression
    - cmd_play_chain_h_activated
  chain_a_shot_hit{advancing==True}:
    - cmd_play_rumble_sound
    - cmd_display_chainsaw_progression
    - cmd_play_chain_a_activated
  chain_i_shot_hit{advancing==True}:
    - cmd_play_rumble_sound
    - cmd_display_chainsaw_progression
    - cmd_play_chain_i_activated
  chain_n_shot_hit{advancing==True}:
    - cmd_play_rumble_sound
    - cmd_display_chainsaw_progression
    - cmd_play_chain_n_activated
  saw_s_shot_hit{advancing==True}:
    - cmd_play_rumble_sound
    - cmd_display_chainsaw_progression
    - cmd_play_saw_s_activated
  saw_a_shot_hit{advancing==True}:
    - cmd_play_rumble_sound
    - cmd_display_chainsaw_progression
    - cmd_play_saw_a_activated
  saw_w_shot_hit{advancing==True}:
    - cmd_play_rumble_sound
    - cmd_display_chainsaw_progression
    - cmd_play_saw_w_activated
  left_orbit{advancing==True}:
    - cmd_turn_off_light__left_orbit
  left_ramp{advancing==True}:
    - cmd_turn_off_light__left_ramp
  right_ramp{advancing==True}:
    - cmd_turn_off_light__left_right_ramp
  right_orbit{advancing==True}:
    - cmd_turn_off_light__right_orbit
  gas_station_shot{advancing==True}:
    - cmd_turn_off_light__gas_station

variable_player:
  cmd_set_chainsaw_variable_off:
    v_chainsaw_multiball_active:
      action: set
      int: 0
  cmd_set_chainsaw_variable_on:
    v_chainsaw_multiball_active:
      action: set
      int: 1

ball_holds:
  bh_sawyer_house:
    balls_to_hold: 1
    hold_devices: bd_sawyer_house
    enable_events: cmd_light_multiball
    disable_events: cmd_disable_sawyer_ball_hold
    release_all_events: cmd_release_sawyer_ball

show_player:
  cmd_light_multiball:
    fast_flash:
      action: play
      show_tokens:
        lights:
          sawyer_house
          chain_target_c
          chain_target_h
          chain_target_a
          chain_target_i
          chain_target_n
          saw_target_s
          saw_target_a
          saw_target_w
  cmd_stop_sawyer_light_flashing:
    fast_flash:
      action: stop
      show_tokens:
        lights:
          sawyer_house
          chain_target_c
          chain_target_h
          chain_target_a
          chain_target_i
          chain_target_n
          saw_target_s
          saw_target_a
          saw_target_w
  cmd_start_shoot_again_flash:
    fast_flash:
      action: play
      show_tokens:
        light: shoot_again
  cmd_stop_shoot_again_flash:
    fast_flash:
      action: stop
      show_tokens:
        light: shoot_again

slides:
  chainsaw_multiball_started_slide:
    - type: image
      image: chainsaw_multiball_start
      fps: 12
  chainsaw_progression_base_slide:
    widgets:
    - type: rectangle
      color: black
      anchor_x: 0
      anchor_y: 0
      x: 0
      y: 0
      width: 128
      height: 32
  chainsaw_shoot_the_house_slide:
    widgets:
    - type: text
      text: SHOOT
      style: dmd_big
      anchor_x: 0
      anchor_y: 0
      x: 73
      y: 17
      animations:
        show_slide: sawyer_flash
    - type: text
      text: THE HOUSE
      style: dmd_big
      anchor_x: 0
      anchor_y: 0
      x: 60
      y: 5
      animations:
        show_slide: sawyer_flash
    - type: image
      image: shoot_the_house_bg
      anchor_x: 0
      anchor_y: 0
      x: 0
      y: 0
  chainsaw_multiball_jackpot_slide:
    widgets:
      - type: image
        image: jackpot_v1_2drip
        fps: 12

slide_player:
  cmd_start_chainsaw_multiball_intro:
    chainsaw_multiball_started_slide:
      priority: 400
      expire: 13.41
  cmd_display_chainsaw_progression:
    chainsaw_progression_base_slide:
      priority: 200
      expire: 2s
  cmd_start_shoot_the_house:
    chainsaw_shoot_the_house_slide:
      priority: 500
      expire: 2s
  cmd_start_jackpot_slide:
    chainsaw_multiball_jackpot_slide:
      priority: 1000
      expire: 2.14s

sound_player:
  cmd_play_rumble_sound: chainsaw_false_start
  cmd_start_chainsaw_multiball_intro: chainsaw_multiball_start
  cmd_start_shoot_the_house:
    three_bells:
      action: play
      loops: 0
      volume: 0.8
  cmd_start_chainsaw_multiball_music:
    frenzy_bg_music:
      action: play
      loops: -1
  cmd_stop_chainsaw_multiball_music:
    frenzy_bg_music:
      action: stop

animations:
  chainsaw_letter_collected:
    - property: y
      value: 2
      duration: 0.05
    - property: y
      value: -1
      duration: 0.05
    - property: y
      value: 1
      duration: 0.05
    - property: y
      value: -3
      duration: 0.05
    - property: y
      value: 2
      duration: 0.05
    - property: y
      value: 1
      duration: 0.05
    - property: y
      value: 0
      duration: 0.05
  sawyer_flash:
    - property: opacity
      value: 1
      duration: 0.1
    - property: opacity
      value: 0
      duration: 0.1
    - property: opacity
      value: 1
      duration: 0.1
    - property: opacity
      value: 0
      duration: 0.1
    - property: opacity
      value: 1
      duration: 0.1
    - property: opacity
      value: 0
      duration: 0.1
    - property: opacity
      value: 1
      duration: 0.1

# animation hack
timers:
  chain_c_animation_timer:
    start_value: 0
    end_value: 1
    tick_interval: 0.1s
    control_events:
      - action: start
        event: cmd_play_chain_c_activated
  chain_h_animation_timer:
    start_value: 0
    end_value: 1
    tick_interval: 0.1s
    control_events:
      - action: start
        event: cmd_play_chain_h_activated
  chain_a_animation_timer:
    start_value: 0
    end_value: 1
    tick_interval: 0.1s
    control_events:
      - action: start
        event: cmd_play_chain_a_activated
  chain_i_animation_timer:
    start_value: 0
    end_value: 1
    tick_interval: 0.1s
    control_events:
      - action: start
        event: cmd_play_chain_i_activated
  chain_n_animation_timer:
    start_value: 0
    end_value: 1
    tick_interval: 0.1s
    control_events:
      - action: start
        event: cmd_play_chain_n_activated
  saw_s_animation_timer:
    start_value: 0
    end_value: 1
    tick_interval: 0.1s
    control_events:
      - action: start
        event: cmd_play_saw_s_activated
  saw_a_animation_timer:
    start_value: 0
    end_value: 1
    tick_interval: 0.1s
    control_events:
      - action: start
        event: cmd_play_saw_a_activated
  saw_w_animation_timer:
    start_value: 0
    end_value: 1
    tick_interval: 0.1s
    control_events:
      - action: start
        event: cmd_play_saw_w_activated
  shoot_the_house_timer:
    start_value: 0
    end_value: 1
    tick_interval: 0.5s
    control_events:
      - event: cmd_light_multiball
        action: start
  chainsaw_multiball_start_timer:
    start_value: 0
    end_value: 1
    tick_interval: 11s
    control_events:
      - event: cmd_start_chainsaw_multiball_start_timer
        action: start

widgets:
  chain_c_background:
    - type: image
      image: chainsaw_c_normal
      style: chainsaw_background_letter_style
  chain_h_background:
    - type: image
      image: chainsaw_h_normal
      style: chainsaw_background_letter_style
  chain_a_background:
    - type: image
      image: chainsaw_a_normal
      style: chainsaw_background_letter_style
  chain_i_background:
    - type: image
      image: chainsaw_i_normal
      style: chainsaw_background_letter_style
  chain_n_background:
    - type: image
      image: chainsaw_n_normal
      style: chainsaw_background_letter_style
  saw_s_background:
    - type: image
      image: chainsaw_s_normal
      style: chainsaw_background_letter_style
  saw_a_background:
    - type: image
      image: chainsaw_a2_normal
      style: chainsaw_background_letter_style
  saw_w_background:
    - type: image
      image: chainsaw_w_normal
      style: chainsaw_background_letter_style
  chain_c_active:
    - type: image
      image: chainsaw_c_fill
      animations:
        timer_chain_c_animation_timer_complete: chainsaw_letter_collected
      style: chainsaw_active_letter_style
  chain_h_active:
    - type: image
      image: chainsaw_h_fill
      animations:
        timer_chain_h_animation_timer_complete: chainsaw_letter_collected
      style: chainsaw_active_letter_style
  chain_a_active:
    - type: image
      image: chainsaw_a_fill
      animations:
        timer_chain_a_animation_timer_complete: chainsaw_letter_collected
      style: chainsaw_active_letter_style
  chain_i_active:
    - type: image
      image: chainsaw_i_fill
      animations:
        timer_chain_i_animation_timer_complete: chainsaw_letter_collected
      style: chainsaw_active_letter_style
  chain_n_active:
    - type: image
      image: chainsaw_n_fill
      animations:
        timer_chain_n_animation_timer_complete: chainsaw_letter_collected
      style: chainsaw_active_letter_style
  saw_s_active:
    - type: image
      image: chainsaw_s_fill
      animations:
        timer_saw_s_animation_timer_complete: chainsaw_letter_collected
      style: chainsaw_active_letter_style
  saw_a_active:
    - type: image
      image: chainsaw_a2_fill
      animations:
        timer_saw_a_animation_timer_complete: chainsaw_letter_collected
      style: chainsaw_active_letter_style
  saw_w_active:
    - type: image
      image: chainsaw_w_fill
      animations:
        timer_saw_w_animation_timer_complete: chainsaw_letter_collected
      style: chainsaw_active_letter_style

widget_player:
  cmd_reset_chainsaw_progression_slide:
    chain_c_background:
      slide: chainsaw_progression_base_slide
    chain_h_background:
      slide: chainsaw_progression_base_slide
    chain_a_background:
      slide: chainsaw_progression_base_slide
    chain_i_background:
      slide: chainsaw_progression_base_slide
    chain_n_background:
      slide: chainsaw_progression_base_slide
    saw_s_background:
      slide: chainsaw_progression_base_slide
    saw_a_background:
      slide: chainsaw_progression_base_slide
    saw_w_background:
      slide: chainsaw_progression_base_slide
  cmd_play_chain_c_activated:
    chain_c_background:
      slide: chainsaw_progression_base_slide
      action: remove
    chain_c_active:
      slide: chainsaw_progression_base_slide
      action: add
  cmd_play_chain_h_activated:
    chain_h_background:
      slide: chainsaw_progression_base_slide
      action: remove
    chain_h_active:
      slide: chainsaw_progression_base_slide
      action: add
  cmd_play_chain_a_activated:
    chain_a_background:
      slide: chainsaw_progression_base_slide
      action: remove
    chain_a_active:
      slide: chainsaw_progression_base_slide
      action: add
  cmd_play_chain_i_activated:
    chain_i_background:
      slide: chainsaw_progression_base_slide
      action: remove
    chain_i_active:
      slide: chainsaw_progression_base_slide
      action: add
  cmd_play_chain_n_activated:
    chain_n_background:
      slide: chainsaw_progression_base_slide
      action: remove
    chain_n_active:
      slide: chainsaw_progression_base_slide
      action: add
  cmd_play_saw_s_activated:
    saw_s_background:
      slide: chainsaw_progression_base_slide
      action: remove
    saw_s_active:
      slide: chainsaw_progression_base_slide
      action: add
  cmd_play_saw_a_activated:
    saw_a_background:
      slide: chainsaw_progression_base_slide
      action: remove
    saw_a_active:
      slide: chainsaw_progression_base_slide
      action: add
  cmd_play_saw_w_activated:
    saw_w_background:
      slide: chainsaw_progression_base_slide
      action: remove
    saw_w_active:
      slide: chainsaw_progression_base_slide
      action: add

#slides:
  #chainsaw_progression_base_slide:
    #widgets:
    #- type: rectangle
      #color: black
      #anchor_x: 0
      #anchor_y: 0
      #x: 0
      #y: 0
      #width: 128
      #height: 32
    #widgets:
      #- type: image
        #image: chainsaw_c_fill
        #anchor_x: 0
        #anchor_y: 0
        #x: 0
        #y: 0
      #- type: image
        #image: chainsaw_h_fill
        #anchor_x: 0
        #anchor_y: 0
        #x: 0
        #y: 0
      #- type: image
        #image: chainsaw_a_fill
        #anchor_x: 0
        #anchor_y: 0
        #x: 0
        #y: 0
      #- type: image
        #image: chainsaw_i_fill
        #anchor_x: 0
        #anchor_y: 0
        #x: 0
        #y: 0
      #- type: image
        #image: chainsaw_n_fill
        #anchor_x: 0
        #anchor_y: 0
        #x: 0
        #y: 0
      #- type: image
        #image: chainsaw_s_fill
        #anchor_x: 0
        #anchor_y: 0
        #x: 0
        #y: 0
      #- type: image
        #image: chainsaw_a2_fill
        #anchor_x: 0
        #anchor_y: 0
        #x: 0
        #y: 0
      #- type: image
        #image: chainsaw_w_fill
        #anchor_x: 0
        #anchor_y: 0
        #x: 0
        #y: 0
